### ISSUE TITLE
api docs missing

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#102]
The API docs are not rendering on readthedocs:

https://pypiper.readthedocs.io/en/latest/api.html

**Comment by nsheff** [comment]
because:
```
/home/sheffien/code/pypiper/doc/source/api.rst:6: WARNING: autodoc: failed to import module u'pypiper.manager'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/sheffien/code/pypiper/pypiper/__init__.py", line 2, in <module>
    from .manager import *
  File "/home/sheffien/code/pypiper/pypiper/manager.py", line 16, in <module>
    import psutil
ImportError: No module named psutil
/home/sheffien/code/pypiper/doc/source/api.rst:13: WARNING: autodoc: failed to import module u'pypiper.ngstk'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/sheffien/code/pypiper/pypiper/__init__.py", line 2, in <module>
    from .manager import *
  File "/home/sheffien/code/pypiper/pypiper/manager.py", line 16, in <module>
    import psutil
ImportError: No module named psutil
```

FYI @michalstolarczyk when adding a dependency you need to also check the docs.

**Comment by michalstolarczyk** [comment]
Do you mean `psutil` library? 

`pypiper` has already been using this one

**Comment by nsheff** [comment]
yep, I think I added it recently.

Turns out the error was in the readthedocs configuration. You can put a requirements file in there so that it will allow importing those. It is now fixed by adjusting that setting.
