### ISSUE TITLE
error handling pipes within parenthetical

### ISSUE THREAD

**Issue by jpsmith5** [databio/pypiper#104]
If a command contains pipes _within_ a set of parenthesis, the command fails.

Example command and reported error:
```
(samtools sort -n -@ 8 /sfs/lustre/allocations/shefflab/processed/gold/pepatac/gold5/hg19/w_pre/samblaster/02/results_pipeline/gold5/aligned_hg19/gold5_sort.bam | samtools view -h -@ 8 | samblaster -r | samtools view -b -@ 8 | samtools sort -@ 8 > /sfs/lustre/allocations/shefflab/processed/gold/pepatac/gold5/hg19/w_pre/samblaster/02/results_pipeline/gold5/aligned_hg19/gold5_sort_dedup.bam)2> /sfs/lustre/allocations/shefflab/processed/gold/pepatac/gold5/hg19/w_pre/samblaster/02/results_pipeline/gold5/aligned_hg19/gold5_dedup_metrics_log.txt

Traceback (most recent call last):
  File "/sfs/lustre/scratch/jps3dp/tools/databio//pepatac/pipelines/pepatac.py", line 1346, in <module>
    sys.exit(main())
  File "/sfs/lustre/scratch/jps3dp/tools/databio//pepatac/pipelines/pepatac.py", line 950, in main
    container=pm.container)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 707, in run
    self.callprint(cmd_i, shell, nofail, container)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 844, in callprint
    processes.append(psutil.Popen(**param_list[i]))
  File "/home/jps3dp/.local/lib/python2.7/site-packages/psutil/__init__.py", line 1308, in __init__
    self.__subproc = subprocess.Popen(*args, **kwargs)
  File "/apps/software/standard/core/anaconda2/4.4.0/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/apps/software/standard/core/anaconda2/4.4.0/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by nsheff** [comment]
two solutions:

1. Bail if we detect this.
2. Try to solve it.

I think if point 2 takes more than a couple of hours to figure out, we go with point 1.

**Comment by jpsmith5** [comment]
See this issue now post commit:

```
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1355, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 682, in main
    outfolder=param.outfolder, aligndir="prealignments")
  File "pipelines/pepatac.py", line 265, in _align_with_bt2
    pm.run(cmd1, out_fastq_bt2, container=pm.container)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 713, in run
    self.callprint(cmd, shell, nofail, container)  # Run command
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 833, in callprint
    param_list = [make_dict(c) for c in split_by_pipes(cmd)] if check_shell_pipes(cmd) else [dict(args=cmd, stdout=None, shell=True)]
NameError: global name 'split_by_pipes' is not defined
```

**Comment by michalstolarczyk** [comment]
Oh, the function wasn't imported in `manager.py`

**Comment by jpsmith5** [comment]
Gotcha, figured it was something simple. Will test again.

**Comment by jpsmith5** [comment]
Issue appears resolved. Will continue testing, but closing for now.
