### ISSUE TITLE
python 3. error

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#121]
```
Traceback (most recent call last):
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 681, in <module>
    main(sys.argv[1:])
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 69, in main
    pm = pypiper.PipelineManager(name="RRBS", outfolder=outfolder, args=args, version=__version__)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 239, in __init__
    self.start_pipeline(args, multi)
  File "/home/ns5bc/.local/lib/python3.6/site-packages/pypiper/manager.py", line 377, in start_pipeline
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)  # Unbuffer output
  File "/apps/software/standard/core/anaconda/5.2.0-py3.6/lib/python3.6/os.py", line 1017, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
OSError: [Errno 9] Bad file descriptor
```

**Comment by nsheff** [comment]
just in the process of testing out python 3 this came up.

**Comment by vreuter** [comment]
Man the inevitable transition to Python 3 is seeming _bumpy_ :worried:

**Comment by afrendeiro** [comment]
Also on Python 3.6.7:
```python
>>> python3 -c "import sys,os;sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/os.py", line 1017, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
```

**Comment by afrendeiro** [comment]
Not sure if relevant but what I'm currently doing to have unbuffered output in a 2/3 compatible manner is this:

```python
class Unbuffered(object):
    def __init__(self, stream):
        self.stream = stream

    def write(self, data):
        self.stream.write(data)
        self.stream.flush()

    def writelines(self, datas):
        self.stream.writelines(datas)
        self.stream.flush()

    def __getattr__(self, attr):
        return getattr(self.stream, attr)


sys.stdout = Unbuffered(sys.stdout)
```

**Comment by vreuter** [comment]
Thanks, it seems like that will likely come in handy regardless.

**Comment by nsheff** [comment]
Just saw a repeat of this error... what's interesting is that it comes up under python 3.6 but not 3.4.

```
python3 hello_pypiper.py 
Removed existing flag: 'hello_pypiper_results/hello_pypiper_completed.flag'
Traceback (most recent call last):
  File "hello_pypiper.py", line 7, in <module>
    pm = pypiper.PipelineManager(name="hello_pypiper", outfolder=outfolder)
  File "/home/sheffien/.local/lib/python3.6/site-packages/pypiper/manager.py", line 239, in __init__
    self.start_pipeline(args, multi)
  File "/home/sheffien/.local/lib/python3.6/site-packages/pypiper/manager.py", line 377, in start_pipeline
    sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)  # Unbuffer output
  File "/usr/lib/python3.6/os.py", line 1017, in fdopen
    return io.open(fd, *args, **kwargs)
ValueError: can't have unbuffered text I/O
sheffien@cd58f238397e:~/code/pypiper/example_pipelines$ 
```
