### ISSUE TITLE
profiles are not being printed

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#127]
My `pipeline_profile.tsv` are not getting lines written to them anymore:

```
 cat RRBS_profile.tsv 
# Pipeline started at 11-20 08:38:35
```

**Comment by nsheff** [comment]
after these updates I'm getting:

```
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1427, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 550, in main
    [args.input, args.input2], raw_folder, args.sample_name)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/ngstk.py", line 301, in merge_or_link
    input_arg, raw_folder, local_base_extended)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/ngstk.py", line 331, in merge_or_link
    shell=True)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 735, in run
    self.callprint(cmd, nofail, container)  # Run command
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 897, in callprint
    self._report_profile(self.procs[current_pid]["proc_name"], lock_file, time.time() - self.procs[current_pid]["start_time"], local_maxmem)
KeyError: 9914
Pipeline status: running

```

**Comment by michalstolarczyk** [comment]
Yes, I've noticed that as well. I'm working on it now...

**Comment by nsheff** [comment]
k thanks

**Comment by michalstolarczyk** [comment]
passes the unit tests after c90dbb2f8f61d6b32a3c7b6b317f1bf87e59144c

**Comment by nsheff** [comment]
can you run it on that pepatac sample with python3 to be sure?

**Comment by michalstolarczyk** [comment]
I'm also running into [this error](https://github.com/databio/pypiper/issues/132) when I'm trying to do so

**Comment by nsheff** [comment]
yeah, you can get around that one by just hard coding it temporarily...

**Comment by michalstolarczyk** [comment]
worked after hardcoding

**Comment by nsheff** [comment]
Ok it's working here too, thanks.
