### ISSUE TITLE
Attmap doesn't populate environment variables

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#132]
See #122 

I believe the switch to `attmap` is the cause of this. When using the `dev` branch, but not `v0.9.4`, any use of a pipeline with environment variables like `${GENOMES}` leads to:

```
### Pipeline failed at:  (03-19 08:12:15) elapsed: 0.0 _TIME_

Total time: 0:00:00

Changed status from running to failed.
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1427, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 496, in main
    _check_bowtie2_index(res.genomes, args.genome_assembly)
  File "pipelines/pepatac.py", line 380, in _check_bowtie2_index
    loc_msg, typ_msg)))
  File "/home/nsheff/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1509, in fail_pipeline
    raise e
IOError: Could not find the 'hg38' index at: ${GENOMES}/hg38/indexed_bowtie2
Try updating/confirming the 'genomes' variable in 'pipelines/pepatac.yaml'.
Confirm that 'hg38' is the correct genome.
```

@vreuter I think this came up before, do you know the easy fix?

```
In [1]: import attmap
In [2]: attmap.__version__
Out[2]: '0.2'
```

That $GENOMES variable in the past was correctly expanded by something.

**Comment by nsheff** [comment]
that did it. thanks.
