### ISSUE TITLE
pypiper callprint maxmem return type is ambiguous

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#133]
Originally raised in https://github.com/databio/pepatac/issues/84

```
python3 pipelines/pepatac.py --single-or-paired paired   --prealignments rCRSd human_repeats   --genome hg38   --sample-name test1   --input examples/data/test1_r1.fastq.gz   --input2 examples/data/test1_r2.fastq.gz   --genome-size hs   -O $HOME/pepatac_test -R
```

Result:
```
> `gzip -d -c /home/nsheff/pepatac_test/test1/raw/test1_R1.fastq.gz > /home/nsheff/pepatac_test/test1/fastq/test1_R1.fastq`

<pre>
</pre>
Process 1100 returned: (0). Elapsed: 0:00:00. Peak memory: (Process: 0.001GB; Pipeline: 0.001GB)
Traceback (most recent call last):
  File "pipelines/pepatac.py", line 1427, in <module>
    sys.exit(main())
  File "pipelines/pepatac.py", line 556, in main
    container=pm.container)
  File "/home/nsheff/.local/lib/python3.5/site-packages/pypiper/manager.py", line 724, in run
    local_maxmem = max(local_maxmem, list_maxmem)
TypeError: unorderable types: list() > int()
Pipeline status: running
```

works under python 2

**Comment by vreuter** [comment]
Sorry...in the commit message I didn't realize the issue is in this repo rather than `pypiper`. Anyway... https://github.com/databio/pypiper/commit/c55e4bd0f16ad0ebee764945879037a53d60b54c

**Comment by nsheff** [comment]
looks like it's working for me. re-open if it not.
