### ISSUE TITLE
SyntaxError on import pypiper; dev branch

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/pypiper#160]
```
[mstolarczyk@MichalsMBP refgenie](dev): pip show piper
Name: piper
Version: 0.12.0.dev0
```

```
[mstolarczyk@MichalsMBP refgenie](dev): ipy
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 05:52:31) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pypiper                                                                               
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-be72a418a439>", line 1, in <module>
    import pypiper

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pypiper/__init__.py", line 2, in <module>
    from .manager import *

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pypiper/manager.py", line 32, in <module>
    from .utils import \

  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pypiper/utils.py", line 287
    not all([isinstance(func_pair, tuple) and len(func_pair) == 2 for func_pair in list(transformations.values()) if isinstance(transformations, Mapping) else transformations]):
                                                                                                                                                             ^
SyntaxError: invalid syntax
```

might be related to this commit: https://github.com/databio/pypiper/commit/45531b534497da15b2822dfdddcf14b400d9031c

**Comment by vreuter** [comment]
Feel free to fix--this appears OSX-specific and I don't have a VM to run it. This occurs on neither 3.5.2 nor 3.6.9 on Ubuntu.
```
Installing collected packages: piper
  Found existing installation: piper 0.12.0.dev0
    Uninstalling piper-0.12.0.dev0:
      Successfully uninstalled piper-0.12.0.dev0
Successfully installed piper-0.12.0.dev0
(py3.6) @ ~/code/pypiper
dev└─ $ git log | head
commit 45531b534497da15b2822dfdddcf14b400d9031c
Author: Vince
Date:   Mon Jul 8 14:52:31 2019 -0400

    fix implementation details and edge cases; test

commit 081f2e77f40db85cae5d8dfef945e3840cdd0d45
Author: Michal Stolarczyk
Date:   Mon Jul 8 12:07:45 2019 -0400

(py3.6) @ ~/code/pypiper
dev└─ $ ipython
Python 3.6.9 (default, Jul  3 2019, 15:36:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pypiper                                                                                                                                                                                      

In [2]:                                                                                                                                                                                                     
```
