### ISSUE TITLE
python exceptions do not correctly change flag

### ISSUE THREAD

**Issue by nsheff** [databio/pypiper#91]
I have a pipeline that is throwing an error, but the flag is not getting correctly changed to `failed`.

It does this: 

```
### Adapter trimming:  (10-25 11:18:45) elapsed: 791.0 _TIME_

Traceback (most recent call last):
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 659, in <module>
    main(sys.argv[1:])
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 109, in main
    if paired: 
NameError: global name 'paired' is not defined

Pypiper terminating spawned child process 86220...(tee)

``` 

but never goes through the failure process.

**Comment by nsheff** [comment]
Can be tested with this simple pipeline:

```

import os
import re
import pypiper
import atexit

__version__="0.2"


print("Testing pypiper")
pm = pypiper.PipelineManager(name="Test", outfolder="test", version=__version__, multi=True)
blah
pm.stop_pipeline()
```

**Comment by nsheff** [comment]
It turned out to be something related to the ordering of the `atexit` functions. If you register the `tee` kill first, then it doesn't work. If you register the `_exit_handler`, which catches this kind of error, after the `tee` kill, then it works.
